name: Release keycrab pipeline
version: 2

runs_on: machine

jobs:
  main:
    - exec:
        - rm -rf dist/ && mkdir -p dist/extensions
        - ext: release/extension.yaml
        - ext: release/server.yaml
