runs_on: machine
version: 2

jobs:
  main:
  - working_dir: ${{bld_project_dir}}
    exec:
    - rm -r dist || true
    - mkdir dist || true
    - ext: release/extension.yaml
    - ext: release/server.yaml
