name: Release keycrab pipeline
version: 2

runs_on: machine

jobs:
  main:
    - exec:
        - rm -r dist/ || true || mkdir dist/ || true
        - ext: release/extension.yaml
        - ext: release/server.yaml
