name: Release keycrab extension pipeline
version: 2

runs_on:
  name: keycrab-image
  dockerfile: ${{ bld_root_dir }}/dockerfiles/Dockerfile
  tag: latest

artifacts:
  - method: get
    from: bld/crates/keycrab_ext/dist
    to: dist/extensions
    after: Build extension ui

jobs:
  main:
    - name: Checkout repository
      exec:
        - git clone https://github.com/Kani-Maki-Gang/keycrab.git

    - name: Build extension ui
      working_dir: keycrab/crates/keycrab_ext
      exec:
        - trunk build --release
