name: Create Github Release
version: 2

runs_on: machine

variables:
  tag: ""
  user: ""
  user_email: ""
  token: ""

jobs:
  main:
    - name: Create release assets
      exec:
        - cp -r ${{ bld_project_dir }}/dist/ ./
        - tar -zcvf keycrab-${{ tag }}.tar.gz dist/

    - name: Get git sha for release
      exec:
        - git rev-parse HEAD > ./git_sha

    - name: Create new tag
      exec:
        - |
          echo '{
            "tag": "${{ tag }}",
            "message": "Release ${{ tag }}",
            "object": "",
            "type": "commit",
            "tagger": {
              "name": "${{ user }}",
              "email": "${{ user_email }}"
            }
          }' > ./tag_data.json
        - cat ./tag_data.json | jq --arg newobj "$(cat ./git_sha)" '.object = $newobj' > tag_request.json
        - |
          curl -s --fail -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Kani-Maki-Gang/keycrab/git/tags \
            -d @tag_request.json \
            > /dev/null

    - name: Create new release
      exec:
        - |
          echo '{
            "tag_name": "${{ tag }}",
            "name": "Release ${{ tag }}",
            "draft": false,
            "prerelease": false,
            "generate_release_notes": true
          }' > release_request.json
        - |
          response=$(curl -s --fail -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Kani-Maki-Gang/keycrab/releases \
            -d @release_request.json)
          echo $response | jq -r .id > ./release_id

    - name: Upload release assets
      exec:
        - |
          curl -s --fail -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @keycrab-${{ tag }}.tar.gz \
            https://uploads.github.com/repos/Kani-Maki-Gang/keycrab/releases/$(cat ./release_id)/assets?name=keycrab-${{ tag }}.tar.gz \
            > /dev/null

