name: Release keycrab server pipeline
version: 2

runs_on:
  name: keycrab-image
  dockerfile: ${{ bld_root_dir }}/dockerfiles/Dockerfile
  tag: latest

variables:
  branch: master

artifacts:
  - method: get
    from: keycrab/target/release/keycrab
    to: dist/
    after: Build backend

jobs:
  main:
    - name: Checkout repository
      exec:
        - git clone -b ${{ branch}} https://github.com/Kani-Maki-Gang/keycrab.git

    - name: Build backend
      working_dir: keycrab
      exec:
        - cargo build --release
