[package]
name = "keycrab_ext"
version = "0.1.0"
edition = "2024"

[dependencies]
keycrab_models = { path = "../../crates/keycrab_models" }
leptos = { version = "0.8.2", features = ["csr"] }
reqwest = { version = "0.12.20", features = ["json"] }
