[package]
name = "keycrab_ext"
version = "0.1.0"
edition = "2024"

[dependencies]
<<<<<<< Updated upstream
dioxus = "0.3.2"
dioxus-web = "0.3.1"
wasm-bindgen = "0.2.87"
tokio = { version = "1.26.0", features = ["rt", "macros", "time"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde-wasm-bindgen = "0.5.0"
wasm-bindgen-futures = "0.4.34"
js-sys = "0.3.61"
console_error_panic_hook = "0.1.7"
reqwest = { version = "0.11.16", features = ["json"] }
anyhow = "1.0.70"
=======
leptos = { version = "0.8.2", features = ["csr"] }
>>>>>>> Stashed changes
