[[hooks]]
stage = "pre_build"
command = "bash"
command_arguments = ["-c", "npm i && npx @tailwindcss/cli -i ./styles.css -o $TRUNK_STAGING_DIR/styles.css"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "mkdir $TRUNK_STAGING_DIR/icons && cp ./icons/* $TRUNK_STAGING_DIR/icons"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "mkdir $TRUNK_STAGING_DIR/font && cp ./font/* $TRUNK_STAGING_DIR/font"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp ./fill_form.js $TRUNK_STAGING_DIR"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp ./manifest.json $TRUNK_STAGING_DIR"]

